<p><a name="contents"></a></p>

# **Diplomado en Lenguajes de Programación: Python, SQL & R.**
# Notas por: **Emmanuel Rivera López.**
## Verano 2024, `versión 1.0.`
# **Lenguaje de Programación Python.** 

- <a href = "#intro"> 1. Introducción </a>
    - <a href="#PhyEaster"> 1.2 Primero lo primero...</a>
- <a href="#DataStrPy">2. Estructura de Datos en el Lenguaje de Programación Python.</a>
    - <a href="#Int">2.1. Números `(int, float)`.</a>
      - <a href="#MathOp">2.1.1. Operadores Aritméticos.</a>
    - <a href="#varassign">2.2. Declaración de Variables.</a>
    - <a href="#Chains">2.3. Cadenas.</a>
    - <a href="#Lists">2.4. Listas.</a>
      - <a href="#lstindex">2.4.1 Indexación de Listas.</a>
    - <a href="#Arr">2.5 Arreglos en Python.</a>
- <a href="#Defunc">3. Funciones Predefinidas.</a>
- <a href="#Lib">4. Bibliotecas y Módulos.</a>
    - <a href="#Numpy">4.1. Biblioteca `NumPy`.</a>
    - <a href="#MtNp">4.2. Métodos dentro de la Biblioteca `NumPy`.</a>
- <a href="#dict">5. Diccionarios.</a>
    - <a href="#dict_att">5.1. Atributos de los Diccionarios</a>
- <a href="#refs">6. Referencias y Cibergrafía.</a>>

<b> Conocimientos Previos:</b> Es importante que tenga los conocimientos esenciales en programación básica <i> variables, estructuras de control, funciones, matrices y el procedimiento de importación de bibliotecas (o módulos, según sea el caso).</i>

<p><a name="intro"></a></p>

# **1. Introducción.**

<p style="text-align: justify;">
El objetivo del primer módulo del Diplomado, es realizar una introducción al Lenguaje de Programación Python. Es importante considerar que se empleará a lo largo de estas sesiones la versión de <b> Python 3.12 </b>, se estudiará la sintaxis básica de del lenguaje, el manejo de cadenas, la creación de funciones, estructuras básicas de datos, importación y manejo de archivos, además de analizar las ventajas que este lenguaje ofrece a comparación de otros bien conocidos dentro del ámbito de la programación. <br><br>
Dado esto, la primer interrogante que surge al introducirse a un nuevo lenguaje de programación, es, valga la redundancia, <i> ¿que es ese lenguaje de programación?, </i> lo cuál de manera natural lleva a preguntarse: 
</p>

<p style="text-align: center;">
   <font size="+1"><b> ¿Qué es el lenguaje Python y porque es importante para usted aprenderlo?</b></font>
</p>
<p style="text-align: justify;">
Python es un lenguaje de programación de alto nivel, multiparadigma cuya filosofía se basa principalmente en <font color = "#2C2C69"><b> su sintaxis ligera y alta versatilidad, la cuál permite máximizar la fácil lectura del mismo, </b></font> lo cuál podría decirse que aventaja a la estructura de lenguajes de programación cómo C, C++ o Java. La <b><i> programación en lenguajes de alto nivel </b></i> es mucho más fácil; escribir programas en un lenguaje de alto nivel
toma menos tiempo, los programas son más cortos y más fáciles de leer, y es más probable que estos programas sean correctos. En segundo lugar, los lenguajes de alto nivel son portables, lo que significa que pueden ejecutarse en tipos diferentes de computadores sin modificación alguna o con pocas modificaciones <br>

De lo anterior, se sigue que estas características permiten que Python no se limite al entorno dinámico que le proporciona al usuario, si no que a su vez <font color = "#873D7D"><b> el lenguaje de programación actúa cómo una solución completa, </b></font> esto por el hecho de que <font color = "#A39512"><b> el lenguaje de programación actúa cómo una solución completa, puede encargarse de gestión de servicios web, cómputo en la nube, manejo y procesamiento de datos, escritura de aplicaciones, tales cómo sitios web dinámicos, aplicaciones para sistemas operativos con interfaces gráficas e inclusive aplicaciones iOS y Android.</b></font>

> "The Python community invested in the mid-1990s in Numeric, an "extension to Python to support numeric analysis as naturally as [M]atlab does". Numeric later evolved into NumPy. Several years later, the plotting functionality from Matlab was ported to Python with matplotlib. Libraries for scientific computing were built around NumPy and matplotlib and bundled into the SciPy package, which was commercially supported by Enthought. Python's support for Matlab-like array manipulation and plotting is a major reason to prefer it over Perl and Ruby.

> Today, the most popular alternatives to Python for data scientists are R, Matlab/Octave, and Mathematica/Sage. In addition to the work mentioned above to port features from Matlab into Python, recent work has ported several popular features from R and Mathematica into Python.

> From R, the data frame and associated manipulations (from the plyr and reshape packages) have been implemented by the pandas library. The scikit-learn project presents a common interface to many machine learning algorithms, similar to the caret package in R."

<div align="right"><b>-Jeff Hammerbacher, Professor at Hammer Lab, founder at Cloudera, investor at Techammer</b></di
</p>
>

<p><a name="PhyEaster"></a></p>

## **1.1. Primero lo primero...**
Los desarrolladores de Python incluyeron ciertas curiosidades y sorpresas dentro de la estructura del lenguaje, a los cuales han llamado <b> Eastereggs (los clásicos huevos de Pascua que uno podría encontrarse en alguna película o videojuego). </b> A continuación, mostraré en consola algunos de los más representativos.

In [2]:
# Importa y devuelve en consola la filosofía tras el Lenguaje de Programación de Python. 
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [6]:
# Devuelve en consola "Hello World".
import __hello__

<p><a name="DataStrPy"></a></p>

# **2. Estructura de Datos en el Lenguaje de Programación Python**

<p style="text-align: justify;">
Python no solo permite guardar un solo valor en una variable, sino que también soporta estructuras de datos que nos facilitan almacenar varios elementos dentro de una sola variable. Estas estructuras en Python funcionan como tipos de datos básicos, cada una con características particulares que las distinguen. <br>
Recuerde que un 'string' o cadena de caracteres es una estructura que organiza el texto <b><i> como una secuencia de caracteres,</b></i> en Python, los objetos que organizarán los valores de un conjunto de datos <i> son los enteros, las listas, los arreglos, conjuntos y los diccionarios.</i>

| Estructura | Sintaxis | Definición |  
| ----- | ----- | ----- |
| **List** | Las listas están encerradas dentro de corchetes: listExample = [1, 2, "a"] | Las listas son ordenadas y modificables. |  
| **Tuple** | Las tuplas se encierran con paréntesis: tupleExample = (1, 2, "a") | Una tupla es ordenada y no puede ser modificada. |  
| **Dictionary** | Los diccionarios se construyen usando llaves: dictionaryExample = {"a":1, "b":2} | Un diccionario no es ordenado, es modificable e indexado. Estos manejan llaves y valores. |  
| **Set** | Los conjuntos se declaran usando también llaves: setExample = {1, 2, 3}. | Un conjunto es una colección no ordenada de elementos. Cada conjunto de elementos es único y se aconseja que no cambie, aunque un conjunto es modificable. |le. |le. |
</p>

<p><a name="Int"></a></p>

## **2.1. Números `int, float`**

<p><a name="MathOp"></a></p>

### **2.1.1 Operadores Aritméticos.**

In [10]:
print(2+7)
print(2*5)
print(7**4)
print(5/85)
# El operador // implementa la función mayor entero y devuelve en consola el mayor inmediato anterior en función de los valores proporcionados por el usuario. 
8//3

9
10
2401
0.058823529411764705


2

<p><a name="varassign"></a></p>

## **2.2. Declaración de variables.**

Las variables (en Python) se declaran mediante el símbolo `=`; esto es, el usuario puede definir variables de la forma `variable_1 = object`.

<div class="alert alert-block alert-info">
Este procedimiento de asignación es sensible a mayúsculas y minúsculas. Esto significa que si declaramos las variables<b> upsilon, Upsilon y UPSILON</b>` serán diferentes.

In [13]:
# Declaración y asignación de una variable en Python 
upsilon = 3.456789
Upsilon = "El alfabeto griego suele emplearse para denominaciones técnicas en la ciencia."
UPSILON = 13 ** 7

In [14]:
upsilon

3.456789

In [15]:
Upsilon

'El alfabeto griego suele emplearse para denominaciones técnicas en la ciencia.'

In [16]:
UPSILON

62748517

In [12]:
altura = 1.95
altura

1.95

<p><a name="Lists"></a></p>

## **2.4. Listas.**

In [20]:
[]

[]

In [21]:
type(["Mario", "Elizabeth", "Emmanuel", "Julio"])

list

In [22]:
# Ejemplo de lista en la cuál las entradas de la misma son valores númericos, observe que estos no se limitan a enteros positivos, el usuario tiene la libertad de 
# ingresar valores negativos, racionales e irracionales. 
number_lst = [-45, 3, 0, 1675, 143, 0.8945112, 6]
number_lst

[-45, 3, 0, 1675, 143, 0.8945112, 6]

In [24]:
string_lst = ["María", "Ciel", "Santiago"]
print(string_lst)
print(type(string_lst))

['María', 'Ciel', 'Santiago']
<class 'list'>


### **2.4.1. Indexación de Listas.**

In [1]:
users_list = ["veteranvanoss", "StragglyCrib1967", "Rinkashisimo"]
users_list

['veteranvanoss', 'StragglyCrib1967', 'Rinkashisimo']

In [2]:
# Insertar un nuevo usuario dentro de la lista en la primera posición. 
users_list.insert(0, "RetroNumericMaster")
# Devuelve en consola la lista con el nuevo usuario.
users_list

['RetroNumericMaster', 'veteranvanoss', 'StragglyCrib1967', 'Rinkashisimo']

<p><a name="Arr"></a></p>

## **2.5. Arreglos en Python.**

<b> ¿Qué es un vector? </b> <br>
Es un elemento en un conjunto, generalmente dentro del espacio $\mathbb{R}^{n}$. Un elemento de $\mathbb{R}^{n}$ forman una ***tupla***. Em el Lenguaje de Programación de Python también existen tuplas, las cuáles no siguen la definición usual que se conoce dentro del campo de las Matemáticas. 
$$\mathbf{x}=(x_{1},x_{2},\ldots, x_{n})$$
en donde cada entrada $x_{i}$ está en los reales. <br>

In [1]:
# Una tupla
type(("a", "b"))

tuple

In [2]:
# Defínanse dos tuplas dentro de Python para posteriormente sumarlas. En Python, al realizar la operación 'x+y', no se obtendrá el resultado usual de la suma de las
# entradas de un espacio vectorial, si no las empleadas para el manejo y análisis de datos
x = (1,2)
y = (3,4)
# Imprime en consola concatenando ambas tuplas.
x+y

(1, 2, 3, 4)

**Observación:** Sean $(x,y)\in \mathbb{R}^{n}$ dos vectores $\mathbf{x}=(x_{1},x_{2}, \ldots, x_{n}) \quad \text{ y } \quad \mathbf{y}=(y_{1},y_{2},\ldots, y_{n})$ <br>
Definimos la suma de $\mathbf{x} \text{ y } \mathbf{y}$ como
$$\mathbf{x+y}=(x_{1}+y_{1},x_{2}+y_{2}, \ldots, x_{n}+y_{n})$$
y se definirá la **multiplicación por un escalar** cómo sigue; sea $\lambda\in \mathbb{R}$, entonces 
$$\lambda \mathbf{x}=(\lambda x_{1},\lambda x_{2}, \ldots, \lambda x_{n})$$

In [3]:
x + (1,-7,4)

(1, 2, 1, -7, 4)

In [4]:
3 * x

(1, 2, 1, 2, 1, 2)

Vamos a definir la operación vectorial a través de listas:

In [5]:
# Definición de una función que permitirá realizar las operaciones nativas sin hacer uso de las bibliotecas dentro del lenguaje de Programación Python 
def prod(x, y):
    z = x * y
    return z

In [6]:
prod(6,12)

72

In [7]:
L_1 = [3, 6, 8, -1, 9]
L_2 = [-8, 1, 0 , 10, 7]
L_1 + L_2

[3, 6, 8, -1, 9, -8, 1, 0, 10, 7]

In [8]:
L_3 = [L_1[0] + L_2[0], L_1[1] + L_2[1], L_1[2] + L_2[2], L_1[3] + L_2[3], L_1[4] + L_2[4]]
L_3

[-5, 7, 8, 9, 16]

In [9]:
L_3i = [L_1[i] + L_2[i] for i in range(len(L_1))]
L_3i

[-5, 7, 8, 9, 16]

In [10]:
L_4 = [2 * L_1[i] for i in range(len(L_1))]
L_4

[6, 12, 16, -2, 18]

In [11]:
def sum_vec(S,T):
    for i in range(len(S)):
        vs = S[i] + T[i] 
        return vs

<p><a name="Defunc"></a></p>

# **3. Funciones Predefinidas.**

In [17]:
dir(__builtins__)

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BaseExceptionGroup',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EncodingWarning',
 'EnvironmentError',
 'Exception',
 'ExceptionGroup',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'Runti

In [18]:
help(eval)

Help on built-in function eval in module builtins:

eval(source, globals=None, locals=None, /)
    Evaluate the given source in the context of globals and locals.

    The source may be a string representing a Python expression
    or a code object as returned by compile().
    The globals must be a dictionary and locals can be any mapping,
    defaulting to the current globals and locals.
    If only globals is given, locals defaults to it.



In [19]:
help(pow)

Help on built-in function pow in module builtins:

pow(base, exp, mod=None)
    Equivalent to base**exp with 2 arguments or base**exp % mod with 3 arguments

    Some types, such as ints, are able to use a more efficient algorithm when
    invoked using the three argument form.



<p><a name="Lib"></a></p>

# **4. Bibliotecas y Módulos.**

<p><a name="Numpy"></a></p>

## **4.1. Biblioteca NumPy**

In [12]:
import numpy as np 

In [13]:
# Definiendo las nuevas variables A_1 y A_2, se están conviritiendo las listas en un vector mediante el uso de la biblioteca NumPy
A_1 = np.array(L_1)
A_2 = np.array(L_2)
A_1 + A_2

array([-5,  7,  8,  9, 16])

In [14]:
A_3 = np.array([4, 13.67])

In [15]:
3 * A_1

array([ 9, 18, 24, -3, 27])

In [16]:
A_1.cumsum()

array([ 3,  9, 17, 16, 25])

In [17]:
A_1.cumprod()

array([    3,    18,   144,  -144, -1296])

In [18]:
A_1.mean()

5.0

<p><a name="MtNp"></a></p>

## **4.2 Métodos dentro de los atributos de la `Biblioteca NumPy`**

In [19]:
# .ndim imprime ne consola la dimensión del vector cómo objeto en Python 
A_1.ndim

1

In [20]:
A_1.shape

(5,)

## **4.3. Matrices Reales.**

In [21]:
M = np.array([[1,2,3], [3,8,9]])
M

array([[1, 2, 3],
       [3, 8, 9]])

In [22]:
N = np.array([[4,0,1], [1,2,-4]])
N

array([[ 4,  0,  1],
       [ 1,  2, -4]])

In [23]:
M + N

array([[ 5,  2,  4],
       [ 4, 10,  5]])

In [24]:
2 * M + N 

array([[ 6,  4,  7],
       [ 7, 18, 14]])

### **Acessos a Elementos de arreglos**

In [25]:
A_1[0]

3

In [26]:
A_1[2:4]

array([ 8, -1])

In [27]:
A_1[0:]

array([ 3,  6,  8, -1,  9])

In [28]:
A_1[2:]

array([ 8, -1,  9])

In [29]:
A_1[ :2]

array([3, 6])

<p><a name="dict"></a></p>

# **5. Diccionarios.**
Son objetos en Python que se crean cómo sigue <br>
$$\{key: objects\}$$
<b> ¿Porque son importantes? </b> <br> 
Son el análogo al Javascript Object Notation (JSON)

In [30]:
{}

{}

In [31]:
type({})

dict

In [32]:
S_1 = {3, 5, 9, -7, 27}
S_2 = {-10, -3, 0, 48.1}

In [33]:
S_1.intersection(S_2)

set()

In [34]:
S_1.union(S_2)

{-10, -7, -3, 0, 3, 5, 9, 27, 48.1}

In [35]:
Clients = {"Id": "2173", 
           "Client": "Emmanuel R. López", 
           "Nationality": "Mexican" }

<p><a name="dict_att"></a></p>

## **5.1. Atributos de los Diccionarios.**

In [36]:
type(Clients.keys())

dict_keys

In [37]:
list(Clients.keys())

['Id', 'Client', 'Nationality']

In [38]:
Clients.values()

dict_values(['2173', 'Emmanuel R. López', 'Mexican'])

In [39]:
Clients.items()

dict_items([('Id', '2173'), ('Client', 'Emmanuel R. López'), ('Nationality', 'Mexican')])

In [40]:
list(Clients.items())

[('Id', '2173'), ('Client', 'Emmanuel R. López'), ('Nationality', 'Mexican')]

# **Referencias y Cibergrafía:**

[1] McKinney, Wes (2018) <i> "Python for Data Analysis: Data wrangling with Pandas, Numpy and IPython". </i> Ed. O'Reilly. <br> 
[2] Galindo López, Julio C. [Julio César Galindo López] <i> Diplomado en Lenguajes de Programación: Python, SQL & R.</i> Sesión 2 [Archivo de Vídeo]. <br>
[3] Galindo López, Julio C. [Julio César Galindo López] <i> Diplomado en Lenguajes de Programación: Python, SQL & R.</i> Sesión 3 [Archivo de Vídeo].